# Copyright 2012 Google Inc.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

application: crisislanding-hr
version: 1
runtime: python27
threadsafe: true
api_version: 1
libraries:
- name: django
  version: "1.3"
- name: PIL
  version: "latest"

# Enabling warmup requests gives us the option to configure idle instances,
# if we need to prepare for traffic spikes ahead of time.  For details, see:
# https://developers.google.com/appengine/docs/adminconsole/performancesettings
inbound_services:
- warmup

handlers:
# Administrative API request handler
- url: .*/remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin

# Static file handlers
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: .*/.static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: .*/.js/(.*).js
  static_files: js/compiled/\1.js
  upload: js/compiled/(.*).js

# User-facing request handlers
- url: .*
  script: app.app
