#!/bin/bash
# Copyright 2012 Google Inc.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

# Starts a Python console connected to an App Engine application.
#
# Usage:
#
# tools/console :8000  # connect to localhost, port 8000
# tools/console xyz.appspot.com  # connect to xyz.appspot.com, port 443
# tools/console :6789 foo.py -- -x  # connect to localhost:6789, run "foo.py -x"

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

export REMOTE_API_RC="
from pprint import *
from model import *
from perms import *
from maps import *
import domains, users, test_utils
test_utils.RootLogin().__enter__()
"
$PYTHON $TOOLS_DIR/remote_api.py "$@"
